type SendEmail = import('./cloudflare-runtime').SendEmail;
/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: 2394930d1d1c42af4856d22a15903be6)
interface __BaseEnv_CloudflareEnv {
	MEDIA_BUCKET: R2Bucket;
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	APP_DB: D1Database;
	NEXT_TAG_CACHE_D1: D1Database;
	AUTH_EMAIL: SendEmail;
	ASSETS: Fetcher;
	AUTH_EMAIL_DELIVERY: "live" | "disabled";
	AUTH_EMAIL_FROM: "noreply@siamrooftech.com";
	NEXT_PUBLIC_GA4_MEASUREMENT_ID: "" | "G-49Q49WM381";
	LINE_CHAT_HISTORY_WORKER_URL: "" | "https://siamrooftech-line-chat-history.phuthan-dev.workers.dev";
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	NEXT_CACHE_DO_QUEUE: DurableObjectNamespace<import("./.open-next/worker").DOQueueHandler>;
	WORKER_SELF_REFERENCE: Fetcher /* siamrooftech-staging */ | Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
		durableNamespaces: "DOQueueHandler";
	}
	interface StagingEnv {
		MEDIA_BUCKET: R2Bucket;
		NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
		APP_DB: D1Database;
		NEXT_TAG_CACHE_D1: D1Database;
		AUTH_EMAIL: SendEmail;
		ASSETS: Fetcher;
		AUTH_EMAIL_DELIVERY: "live";
		AUTH_EMAIL_FROM: "noreply@siamrooftech.com";
		NEXT_PUBLIC_GA4_MEASUREMENT_ID: "";
		LINE_CHAT_HISTORY_WORKER_URL: "";
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		NEXT_CACHE_DO_QUEUE: DurableObjectNamespace<import("./.open-next/worker").DOQueueHandler>;
		WORKER_SELF_REFERENCE: Fetcher /* siamrooftech-staging */;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_EMAIL_DELIVERY" | "AUTH_EMAIL_FROM" | "NEXT_PUBLIC_GA4_MEASUREMENT_ID" | "LINE_CHAT_HISTORY_WORKER_URL" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL">> {}
}
