type SendEmail = import('./cloudflare-runtime').SendEmail;
/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: 3bd22bfe19fdae65208a36bfea277dfd)
interface __BaseEnv_CloudflareEnv {
	MEDIA_BUCKET: R2Bucket;
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	APP_DB: D1Database;
	NEXT_TAG_CACHE_D1: D1Database;
	AUTH_EMAIL: SendEmail;
	ASSETS: Fetcher;
	DEPLOY_ENV: "staging" | "production" | "local";
	SITE_ORIGIN: "https://staging.siamrooftech.com" | "https://www.siamrooftech.com" | "http://localhost:3000";
	INDEX_POLICY: "noindex" | "index";
	AUTH_EMAIL_DELIVERY: "live" | "disabled";
	AUTH_EMAIL_FROM: "noreply@siamrooftech.com";
	NEXT_PUBLIC_GA4_MEASUREMENT_ID: "" | "G-49Q49WM381";
	LINE_CHAT_HISTORY_WORKER_URL: "" | "https://siamrooftech-line-chat-history.phuthan-dev.workers.dev";
	NEXT_CACHE_DO_QUEUE: DurableObjectNamespace<import("./.open-next/worker").DOQueueHandler>;
	WORKER_SELF_REFERENCE: Fetcher /* siamrooftech-staging */ | Fetcher /* siamrooftech */ | Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
		durableNamespaces: "DOQueueHandler";
	}
	interface StagingEnv {
		MEDIA_BUCKET: R2Bucket;
		NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
		APP_DB: D1Database;
		NEXT_TAG_CACHE_D1: D1Database;
		AUTH_EMAIL: SendEmail;
		ASSETS: Fetcher;
		DEPLOY_ENV: "staging";
		SITE_ORIGIN: "https://staging.siamrooftech.com";
		INDEX_POLICY: "noindex";
		AUTH_EMAIL_DELIVERY: "live";
		AUTH_EMAIL_FROM: "noreply@siamrooftech.com";
		NEXT_PUBLIC_GA4_MEASUREMENT_ID: "";
		LINE_CHAT_HISTORY_WORKER_URL: "";
		NEXT_CACHE_DO_QUEUE: DurableObjectNamespace<import("./.open-next/worker").DOQueueHandler>;
		WORKER_SELF_REFERENCE: Fetcher /* siamrooftech-staging */;
	}
	interface ProductionEnv {
		MEDIA_BUCKET: R2Bucket;
		NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
		APP_DB: D1Database;
		NEXT_TAG_CACHE_D1: D1Database;
		AUTH_EMAIL: SendEmail;
		ASSETS: Fetcher;
		DEPLOY_ENV: "production";
		SITE_ORIGIN: "https://www.siamrooftech.com";
		INDEX_POLICY: "index";
		AUTH_EMAIL_DELIVERY: "live";
		AUTH_EMAIL_FROM: "noreply@siamrooftech.com";
		NEXT_PUBLIC_GA4_MEASUREMENT_ID: "G-49Q49WM381";
		LINE_CHAT_HISTORY_WORKER_URL: "https://siamrooftech-line-chat-history.phuthan-dev.workers.dev";
		NEXT_CACHE_DO_QUEUE: DurableObjectNamespace<import("./.open-next/worker").DOQueueHandler>;
		WORKER_SELF_REFERENCE: Fetcher /* siamrooftech */;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOY_ENV" | "SITE_ORIGIN" | "INDEX_POLICY" | "AUTH_EMAIL_DELIVERY" | "AUTH_EMAIL_FROM" | "NEXT_PUBLIC_GA4_MEASUREMENT_ID" | "LINE_CHAT_HISTORY_WORKER_URL">> {}
}
