/**
 * Extended Article Types for SEO-first Mobile CMS
 * Based on: /docs/design-system/ARTICLE_CMS_UX_OVERHAUL.md
 */

import { Article as BaseArticle } from '../lib/firestore';

// ===== SEO Analysis Types =====

export interface ContentAnalysis {
  readabilityScore: number; // 0-100 (Flesch Reading Ease adapted for Thai)
  keywordDensity: { [keyword: string]: number }; // Percentage
  headingStructure: string[]; // H1-H6 list
  internalLinks: number;
  externalLinks: number;
  imageCount: number;
  imagesWithAlt: number;
  wordCount: number;
  sentenceCount: number;
  avgWordsPerSentence: number;
  avgSentencesPerParagraph: number;
}

export interface SeoReadinessCheck {
  titleOptimal: boolean; // 50-60 chars
  descriptionOptimal: boolean; // 120-160 chars
  keywordInTitle: boolean;
  keywordInFirstParagraph: boolean;
  keywordInHeadings: boolean;
  hasInternalLinks: boolean; // At least 2
  allImagesHaveAlt: boolean;
  noDuplicateTitle: boolean;
  slugOptimal: boolean; // No special chars, < 60 chars
  readabilityGood: boolean; // Score > 60
}

export interface SeoReadiness {
  score: number; // 0-100 (calculated from checks)
  checks: SeoReadinessCheck;
  suggestions: string[]; // Thai language suggestions
  criticalIssues: string[]; // Blocking issues
  warnings: string[]; // Non-blocking issues
}

export interface TopicCoverageTopics {
  pricing: boolean; // ราคา
  types: boolean; // ประเภท
  materials: boolean; // วัสดุ
  installation: boolean; // วิธีติดตั้ง
  maintenance: boolean; // การดูแล
  pros: boolean; // ข้อดี
  cons: boolean; // ข้อจำกัด/ข้อเสีย
  faq: boolean; // คำถามพบบ่อย
}

export interface TopicCoverage {
  topics: TopicCoverageTopics;
  coverageScore: number; // 0-100 (percentage of topics covered)
  missingTopics: string[]; // Thai labels of missing topics
  suggestions: string[]; // Suggestions for missing topics
}

export interface AutoGeneratedMeta {
  title: string; // Generated from title + keyword optimization
  description: string; // First paragraph or auto-summarized
  keywords: string[]; // Extracted keywords
  generatedAt: string; // ISO timestamp
  confidence: number; // 0-100
}

export interface DraftVersion {
  timestamp: string; // ISO timestamp
  content: string; // Full article JSON
  autoSaved: boolean; // true if autosaved, false if manual
  wordCount: number;
}

export interface InternalLinkSuggestion {
  articleId: string;
  articleTitle: string;
  articleSlug: string;
  relevanceScore: number; // 0-100
  suggestedAnchor: string; // Suggested anchor text
  context: string; // Where to place it (paragraph snippet)
}

// ===== Extended Article Interface =====

export interface ArticleExtended extends BaseArticle {
  // Zero-Config SEO fields
  autoGeneratedSlug?: string;
  autoGeneratedMeta?: AutoGeneratedMeta;

  // Content Analysis
  contentAnalysis?: ContentAnalysis;

  // SEO Readiness
  seoReadiness?: SeoReadiness;

  // Topic Coverage (for primary keyword: "กันสาดพับได้")
  topicCoverage?: TopicCoverage;

  // Autosave & Recovery
  draftVersions?: DraftVersion[];
  lastAutoSave?: string; // ISO timestamp
  hasUnsavedChanges?: boolean;

  // Internal Linking Suggestions
  suggestedInternalLinks?: InternalLinkSuggestion[];

  // Performance metrics
  processingTime?: number; // Time to analyze (ms)
  lastAnalyzedAt?: string; // ISO timestamp
}

// ===== Form State Types =====

export interface ArticleFormData {
  // Basic fields
  title: string;
  excerpt: string;
  content: string;
  featured_image?: string;
  category: string;
  author: string;
  tags: string[];
  slug: string;
  read_time: string;

  // SEO fields
  seoTitle: string;
  seoDescription: string;
  seoKeywords: string[];
  isPublished: boolean;

  // Editor state
  currentTab: 'พื้นฐาน' | 'เนื้อหา' | 'SEO';
  isDirty: boolean;
  lastSaved?: Date;
  isAnalyzing?: boolean;
}

// ===== Validation Types =====

export interface ArticleValidationResult {
  valid: boolean;
  errors: string[]; // Blocking errors
  warnings: string[]; // Non-blocking warnings
  criticalCount: number;
  warningCount: number;
}

export interface PublishChecklistItem {
  id: string;
  label: string;
  status: boolean;
  severity: 'critical' | 'recommended' | 'optional';
  fixAction?: () => void | string; // Function or "แก้ไขเลย" button action
  helpText?: string;
}

export interface PublishChecklist {
  critical: PublishChecklistItem[];
  recommended: PublishChecklistItem[];
  optional?: PublishChecklistItem[];
  overallStatus: 'ready' | 'needs-fixes' | 'has-warnings';
  readyToPublish: boolean;
}

// ===== Keyword Analysis Types =====

export interface KeywordAnalysis {
  keyword: string;
  found: boolean;
  positions: {
    inTitle: boolean;
    inFirstParagraph: boolean;
    inHeadings: number; // Count
    inContent: number; // Count
  };
  density: number; // 0-100 percentage
  prominence: number; // 0-100 score
  suggestions: string[]; // Where to add keyword
  relatedKeywords: string[]; // Synonyms/related terms
}

// ===== Content Cleaner Types =====

export interface PasteCleanupResult {
  cleaned: string; // Cleaned markdown
  removed: {
    styles: number;
    scripts: number;
    trackingPixels: number;
    emptyTags: number;
    comments: number;
  };
  converted: {
    tables: number;
    lists: number;
    headings: number;
    links: number;
  };
  warnings: string[];
  source: 'word' | 'google-docs' | 'html' | 'markdown' | 'unknown';
}

// ===== SERP Preview Types =====

export interface SerpPreviewData {
  title: string; // Display title (seoTitle or title)
  description: string; // Display description (seoDescription or excerpt)
  url: string; // Full URL
  slug: string;
  isTitleTruncated: boolean;
  isDescriptionTruncated: boolean;
  titleLength: number;
  descriptionLength: number;
}

// ===== Constants =====

export const ARTICLE_CATEGORIES = [
  'เทคนิคและคำแนะนำ',
  'การดูแลรักษา',
  'การติดตั้ง',
  'แนะนำผลิตภัณฑ์',
  'ข่าวสาร',
  'อื่นๆ',
] as const;

export type ArticleCategory = typeof ARTICLE_CATEGORIES[number];

export const PRIMARY_KEYWORD = 'กันสาดพับได้';

export const SEO_LIMITS = {
  TITLE_MIN: 30,
  TITLE_MAX: 60,
  TITLE_OPTIMAL: 55,
  DESCRIPTION_MIN: 70,
  DESCRIPTION_MAX: 160,
  DESCRIPTION_OPTIMAL: 155,
  SLUG_MAX: 60,
  TAGS_MAX: 7,
  KEYWORDS_MAX: 10,
  EXCERPT_MAX: 200,
  MIN_WORD_COUNT: 300,
  MIN_INTERNAL_LINKS: 2,
  MAX_INTERNAL_LINKS: 10,
  OPTIMAL_KEYWORD_DENSITY: 2, // 2% optimal
  MAX_KEYWORD_DENSITY: 5, // 5% too much
  AUTOSAVE_INTERVAL: 3000, // 3 seconds (Doherty Threshold)
  MAX_DRAFT_VERSIONS: 10,
} as const;

export const READABILITY_THRESHOLDS = {
  EXCELLENT: 80,
  GOOD: 60,
  FAIR: 40,
  DIFFICULT: 20,
} as const;

export const TOPIC_COVERAGE_KEYWORDS = {
  pricing: ['ราคา', 'เท่าไหร่', 'ค่าใช้จ่าย', 'งบประมาณ', 'บาท', 'price'],
  types: ['ประเภท', 'แบบ', 'รูปแบบ', 'ชนิด', 'model', 'type'],
  materials: ['วัสดุ', 'ผ้า', 'โครงสร้าง', 'คุณภาพ', 'material', 'fabric'],
  installation: ['ติดตั้ง', 'วิธีติดตั้ง', 'การติดตั้ง', 'install', 'setup'],
  maintenance: ['ดูแล', 'บำรุงรักษา', 'ทำความสะอาด', 'maintain', 'care'],
  pros: ['ข้อดี', 'ประโยชน์', 'เหมาะ', 'ดี', 'advantage', 'benefit'],
  cons: ['ข้อจำกัด', 'ข้อเสีย', 'ไม่เหมาะ', 'disadvantage', 'limitation'],
  faq: ['คำถาม', 'faq', 'ถาม', 'ตอบ', 'question'],
} as const;
